### PR TITLE
Add support P11, P12 and fix #60

### LINKED ISSUE #60: Instance of SQLite3Library did not understand #stringFrom:at:
Running the following in a Playground:

| connection cursor |
connection := SQLite3Connection memory.
connection open.
connection execute: 'CREATE TABLE person(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
);'.

connection execute: 'INSERT INTO person(name,age) VALUES (:name, :age);' with: {
  ':name' -> 'Guillaume'.
  ':age' -> 30 } asDictionary.

cursor := connection execute: 'SELECT * FROM person;'.
cursor rows

The walkback window shows the error raised at line 6 in the stringAt: method for the SQLite3PreparedStatement class.

The image is Pharo 12, 64-bit, on Ubuntu Linux 22.04
The same error appears when using a Pharo 10, 64-bit image on the same Ubuntu Linux 22.04
The same error also appears on my Windows 11 machine, running a Pharo 12 image (64-bit)

On Linux, the version of sqlite is: 3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837bb4d6

I've run just the create table command, and that executes with no issues. I can also run the execute: method and that returns acceptable. It's only when I attempt to fetch a row that the walkback occurs.

### PR DESCRIPTION
**Pull request by astares**
fix #60

### CODE REVIEW

**Comment by astares** [comment]
Mmmhhh .... strange: CI throws an primitive error in Threaded FFI (TFFI) Backend

image

@tesonep can you help

**Comment by astares** [comment]
To reproduce load Glorp into latest Pharo 12 on Windows and run #testTime

**Comment by gcotelli** [comment]
I'm researching this a bit and seems that the data written in the DB is not right for `datetime` and `time` columns. So maybe the problem is in the storing function calls and not in the retrieval ones.

**Comment by gcotelli** [comment]
I've found the problem. The methods putting dates, date times, and times are not encoding the string representations as UTF8. I don't know why it worked previously, maybe some FFI changes broke it?

**Pull request closed without merging**
